spring:
  application:
    name: auth-service
  cloud:
    kubernetes:
      enabled: false

grpc:
  client:
    user-service:
      address: static://user-service:8080
      negotiation-type: plaintext
    common-service:
      address: static://common-service:8080
      negotiation-type: plaintext
management:
  endpoints:
    web.exposure.include: health,info
  endpoint.health.probes.enabled: true
