server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: auth-service
#  autoconfigure:
#    exclude:
#      # 避免 grpc-server-spring-boot-starter 在检测到 AuthenticationManager 后自动装配 gRPC 安全拦截器
#      # 该自动配置会强制要求提供 GrpcAuthenticationReader（当前项目未使用 gRPC 层面的 Spring Security）
#      - net.devh.boot.grpc.server.autoconfigure.GrpcServerSecurityAutoConfiguration
  cloud:
    nacos:
      server-addr: localhost:8848
      config:
        enabled: false
        file-extension: yaml
        shared-configs:
          - data-id: shared-spring.yaml
            refresh: false
          - data-id: shared-redis.yaml
            refresh: false
          - data-id: shared-mybatis.yaml
            refresh: false
          - data-id: shared-logs.yaml
            refresh: false
      discovery:
        enabled: false
        register-enabled: false
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
grpc:
  server:
    port: 9091  # gRPC服务端口
  client:
    user-service:
      address: static://127.0.0.1:9090
      negotiation-type: plaintext
