spring:
  application:
    name: auth-service
  cloud:
    kubernetes:
      enabled: false

grpc:
  client:
    user-service:
      address: dns:///user-service:8080
      negotiation-type: plaintext
      enable-keep-alive: true
      keep-alive-time: 30s
      keep-alive-timeout: 10s
      keep-alive-without-calls: false
    common-service:
      address: dns:///common-service:8080
      negotiation-type: plaintext
      enable-keep-alive: true
      keep-alive-time: 30s
      keep-alive-timeout: 10s
      keep-alive-without-calls: false
management:
  endpoints:
    web.exposure.include: health,info
  endpoint.health.probes.enabled: true
