spring:
  application:
    name: auth-service
  cloud:
    kubernetes:
      enabled: true
      discovery:
        enabled: true
        all-namespaces: false
        include-not-ready-addresses: false
        primary-port-name: grpc

grpc:
  client:
    user-service:
      address: discovery:///user-service
      defaultLoadBalancingPolicy: round_robin
      negotiation-type: plaintext
    common-service:
      address: discovery:///common-service
      defaultLoadBalancingPolicy: round_robin
      negotiation-type: plaintext
management:
  endpoints:
    web.exposure.include: health,info
  endpoint.health.probes.enabled: true
