server:
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: auth-service
  cloud:
    kubernetes:
      enabled: false
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

auth:
  remote-config:
    enabled: true
    fail-fast: true
    nacos-data-id: auth-service.key.config
    redis-data-id: auth-service.core.config
    timeout-ms: 3000

grpc:
  server:
    port: 9090
  client:
    user-service:
      address: dns:///user-service:8080
      negotiation-type: plaintext
      enable-keep-alive: true
      keep-alive-time: 30s
      keep-alive-timeout: 10s
      keep-alive-without-calls: false
    common-service:
      address: dns:///common-service:8080
      negotiation-type: plaintext
      enable-keep-alive: true
      keep-alive-time: 30s
      keep-alive-timeout: 10s
      keep-alive-without-calls: false
management:
  endpoints:
    web.exposure.include: health,info
  endpoint.health.probes.enabled: true
