spring:
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos注册中心
      discovery:
        namespace: f923fb34-cb0a-4c06-8fca-ad61ea61a3f0
        group: DEFAULT_GROUP
        ip: localhost
logging:
  level:
    com.astraios: debug