apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-service.fullname" . }}-config
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
data:
  user.yaml: |
    Name: {{ .Values.config.name }}
    ListenOn: {{ .Values.config.listenOn }}
    Timeout: {{ .Values.config.timeout }}
    CpuThreshold: {{ .Values.config.cpuThreshold }}
    Middlewares:
      Breaker: {{ .Values.config.middlewares.breaker }}
    ConfigDataId: {{ .Values.config.configDataId }}
    CommonService:
      Endpoints:
{{ toYaml .Values.config.commonService.endpoints | nindent 8 }}
      Timeout: {{ .Values.config.commonService.timeout }}
      NonBlock: {{ .Values.config.commonService.nonBlock }}
      Middlewares:
        Breaker: {{ .Values.config.commonService.middlewares.breaker }}
