apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-service.fullname" . }}
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: rpc
      port: {{ .Values.service.port }}
      targetPort: rpc
      protocol: TCP
  selector:
    {{- include "user-service.selectorLabels" . | nindent 4 }}
