apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common-service.fullname" . }}-config
  labels:
    {{- include "common-service.labels" . | nindent 4 }}
data:
  common.yaml: |
    Name: {{ .Values.config.name }}
    ListenOn: {{ .Values.config.listenOn }}
    Timeout: {{ .Values.config.timeout }}
    CpuThreshold: {{ .Values.config.cpuThreshold }}
    Middlewares:
      Breaker: {{ .Values.config.middlewares.breaker }}
