{{- if and .Values.nacos.enabled (not .Values.nacos.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common-service.fullname" . }}-nacos
  labels:
    {{- include "common-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  serverAddr: {{ .Values.nacos.serverAddr | quote }}
  username: {{ .Values.nacos.username | quote }}
  password: {{ .Values.nacos.password | quote }}
  namespace: {{ .Values.nacos.namespace | quote }}
  group: {{ .Values.nacos.group | quote }}
  dataIdSuffix: {{ .Values.nacos.dataIdSuffix | quote }}
{{- end }}
