apiVersion: v1
kind: Service
metadata:
  name: {{ include "nacos.fullname" . }}
  labels:
    {{- include "nacos.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8848
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpcPort1 }}
      targetPort: 9848
      protocol: TCP
      name: grpc-1
    - port: {{ .Values.service.grpcPort2 }}
      targetPort: 9849
      protocol: TCP
      name: grpc-2
  selector:
    {{- include "nacos.selectorLabels" . | nindent 4 }}
